name: Check Build
on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'
    paths:
      - '**'
jobs:
  CheckBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          golang-version: 1.19
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checked Make Build
        run: |
          make build
