name: Check Build
on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'
    paths:
      - '**'
jobs:
  CheckBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          golang-version: 1.19
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup yarn
        id: yarn-cache-dir-path
        run: |
          npm install -g yarn
          echo "::set-output name=dir::$(yarn cache dir)"
      - name: Checked Make Build
        run: |
          if [ -n "$$NVM_DIR" ]
          then
            nvm install
          fi
          make build
